import type { CSSProperties } from "react";

export const COLOR_RED = "#F21D2F";
export const COLOR_BLUE = "#161A59";
export const COLOR_GRAY = "#E3E4EA";

export const styles: Record<string, CSSProperties> = {
  page: { padding: 18 },
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1.4fr 1fr",
    gap: 16,
    alignItems: "stretch",
  },
  col: { display: "flex", flexDirection: "column", gap: 16, minWidth: 0 },
  center: { minWidth: 0 },
  infoBox: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: "rgba(15, 23, 42, 0.04)",
    marginBottom: 12,
    fontSize: 13,
  },
  errorBox: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: "rgba(242, 29, 47, 0.12)",
    marginBottom: 12,
    fontSize: 13,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  retryBtn: {
    border: "1px solid rgba(15, 23, 42, 0.15)",
    background: "#fff",
    borderRadius: 10,
    padding: "8px 12px",
    cursor: "pointer",
    fontWeight: 800,
  },
  cardButton: {
    border: "none",
    background: "transparent",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 16,
    boxShadow: "0 6px 18px rgba(0,0,0,0.08)",
    border: "1px solid rgba(22, 26, 89, 0.10)",
    width: "100%",
    boxSizing: "border-box",
  },
  cardTop: { display: "flex", gap: 10, alignItems: "center", minWidth: 0 },
  cardIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(22, 26, 89, 0.08)",
    flexShrink: 0,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "#161A59",
    lineHeight: 1.2,
    minWidth: 0,
  },
  cardValueRow: {
    marginTop: 10,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 10,
    minWidth: 0,
  },
  cardValue: { fontSize: 34, fontWeight: 900, color: "#0F172A", letterSpacing: -0.5 },
  cardCta: {
    fontSize: 12,
    fontWeight: 900,
    color: "#F21D2F",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  cardSub: { marginTop: 6, fontSize: 12, color: "rgba(15, 23, 42, 0.75)" },
  panel: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 16,
    boxShadow: "0 6px 18px rgba(0,0,0,0.08)",
    border: "1px solid rgba(22, 26, 89, 0.10)",
    minHeight: 210,
    minWidth: 0,
    overflow: "hidden",
    boxSizing: "border-box",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap",
    rowGap: 10,
    minWidth: 0,
  },
  panelTitle: { fontSize: 15, fontWeight: 900, color: "#161A59" },
  panelSubtitle: { marginTop: 3, fontSize: 12, color: "rgba(15, 23, 42, 0.65)" },
  headerRight: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 8,
    maxWidth: "100%",
    minWidth: 0,
  },
  select: {
    border: `1px solid ${COLOR_GRAY}`,
    borderRadius: 10,
    padding: "8px 10px",
    fontSize: 12,
    fontWeight: 800,
    background: "#fff",
    cursor: "pointer",
    color: "rgba(15, 23, 42, 0.85)",
    width: "clamp(140px, 18vw, 200px)",
    maxWidth: "100%",
    minWidth: 0,
    boxSizing: "border-box",
  },
  chartBox: { marginTop: 12, height: 220, minWidth: 0 },
  weekNav: {
    display: "flex",
    gap: 8,
    flexWrap: "nowrap",
    flexShrink: 0,
  },
  weekBtn: {
    border: `1px solid ${COLOR_GRAY}`,
    background: "#fff",
    borderRadius: 10,
    width: 34,
    height: 34,
    padding: 0,
    fontWeight: 900,
    cursor: "pointer",
    flexShrink: 0,
  },
  hintRow: { marginTop: 10, display: "flex", gap: 8, alignItems: "center" },
  hintDot: { width: 10, height: 10, borderRadius: 999, backgroundColor: COLOR_BLUE },
  hintText: { fontSize: 12, color: "rgba(15, 23, 42, 0.70)", fontWeight: 700 },
  badge: {
    fontSize: 12,
    fontWeight: 900,
    padding: "6px 10px",
    borderRadius: 999,
    backgroundColor: "rgba(242, 29, 47, 0.10)",
    color: COLOR_RED,
    flexShrink: 0,
  },
  empty: {
    padding: 14,
    borderRadius: 12,
    backgroundColor: "rgba(15, 23, 42, 0.04)",
    color: "rgba(15, 23, 42, 0.70)",
    fontSize: 13,
  },
  list: { display: "flex", flexDirection: "column", gap: 10, minWidth: 0 },
  listRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    padding: 12,
    borderRadius: 12,
    border: "1px solid rgba(15, 23, 42, 0.10)",
    backgroundColor: "rgba(15, 23, 42, 0.02)",
    alignItems: "center",
    minWidth: 0,
  },
  listLeft: { minWidth: 0, flex: 1 },
  listTime: { fontSize: 12, fontWeight: 900, color: "#0F172A" },
  listMain: { marginTop: 4, display: "flex", gap: 6, flexWrap: "wrap", alignItems: "center" },
  listClient: { fontSize: 13, fontWeight: 900, color: "#161A59" },
  listService: { fontSize: 13, fontWeight: 800, color: "rgba(15, 23, 42, 0.85)" },
  listMeta: { marginTop: 4, fontSize: 12, color: "rgba(15, 23, 42, 0.65)" },
  dot: { color: "rgba(15, 23, 42, 0.35)", fontWeight: 900 },
  statusPill: {
    fontSize: 12,
    fontWeight: 900,
    padding: "6px 10px",
    borderRadius: 999,
    backgroundColor: "rgba(22, 26, 89, 0.10)",
    color: "#161A59",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  overlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(2, 6, 23, 0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
    padding: 16,
  },
  modal: {
    width: "min(860px, 96vw)",
    backgroundColor: "#fff",
    borderRadius: 16,
    boxShadow: "0 18px 50px rgba(0,0,0,0.35)",
    border: "1px solid rgba(15, 23, 42, 0.12)",
    overflow: "hidden",
  },
  modalHeader: {
    padding: "14px 16px",
    borderBottom: "1px solid rgba(15, 23, 42, 0.08)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  modalTitle: { fontSize: 16, fontWeight: 900, color: "#161A59" },
  modalSubtitle: { marginTop: 3, fontSize: 12, color: "rgba(15, 23, 42, 0.65)" },
  closeBtn: {
    border: `1px solid ${COLOR_GRAY}`,
    background: "#fff",
    borderRadius: 10,
    width: 34,
    height: 34,
    cursor: "pointer",
    fontWeight: 900,
    color: "rgba(15, 23, 42, 0.8)",
  },
  modalBody: { padding: 16 },
  modalFooter: {
    padding: "12px 16px",
    borderTop: "1px solid rgba(15, 23, 42, 0.08)",
    display: "flex",
    justifyContent: "flex-end",
  },
  modalList: { display: "flex", flexDirection: "column", gap: 10 },
  modalRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    padding: 12,
    borderRadius: 12,
    border: `1px solid ${COLOR_GRAY}`,
    backgroundColor: "rgba(15, 23, 42, 0.02)",
    alignItems: "center",
  },
  modalRowRight: { display: "flex", gap: 10, alignItems: "center" },
  eyeBtn: {
    border: `1px solid ${COLOR_GRAY}`,
    background: "#fff",
    borderRadius: 10,
    width: 34,
    height: 34,
    cursor: "pointer",
    fontSize: 16,
    lineHeight: "34px",
    textAlign: "center",
  },
  modalRowTitle: { fontSize: 13, fontWeight: 900, color: "#0F172A" },
  modalRowSub: { marginTop: 4, fontSize: 12, color: "rgba(15, 23, 42, 0.65)" },
  muted: { color: "rgba(15, 23, 42, 0.45)", fontWeight: 900 },
  tag: {
    fontSize: 12,
    fontWeight: 900,
    padding: "6px 10px",
    borderRadius: 999,
    whiteSpace: "nowrap",
  },
  tagWarn: { backgroundColor: "rgba(242, 29, 47, 0.12)", color: COLOR_RED },
  tagInfo: { backgroundColor: "rgba(22, 26, 89, 0.12)", color: COLOR_BLUE },
  tagDanger: { backgroundColor: "rgba(242, 29, 47, 0.12)", color: COLOR_RED },
  tagOk: { backgroundColor: "rgba(22, 26, 89, 0.10)", color: COLOR_BLUE },
  pager: { display: "flex", gap: 10, alignItems: "center" },
  pagerBtn: {
    border: `1px solid ${COLOR_GRAY}`,
    background: "#fff",
    borderRadius: 10,
    padding: "6px 10px",
    fontWeight: 900,
  },
  pagerText: { fontSize: 12, color: "rgba(15, 23, 42, 0.70)" },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  },
  detailRow: {
    border: `1px solid ${COLOR_GRAY}`,
    borderRadius: 12,
    padding: 12,
    backgroundColor: "rgba(15, 23, 42, 0.02)",
  },
  detailLabel: { fontSize: 12, color: "rgba(15, 23, 42, 0.65)", fontWeight: 800 },
  detailValue: { marginTop: 6, fontSize: 13, fontWeight: 900, color: "#0F172A" },
};